language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

services: mysql

env:
  - DJANGO="django==1.10.4" DB="mysql"
  - DJANGO="django==1.8.17" DB="mysql"

install:
  - pip install $DJANGO
  - pip install celery==3.1.24
  - pip install coveralls
  - pip install mysqlclient

before_script:
  - mysql -e 'create database testdb;'

script:
  - coverage run --source=djcelery_transactions runtests.py

after_success:
  coveralls
